site: Florian Bader
url: florian-bader.de
title: Florian Bader
description: Aus dem Leben eines Entwicklers
twitter:
  username: FlorianBaderDE
  card: summary
  creator: Florian Bader
author:
  twitter: FlorianBaderDE
  name: FlorianBader
  avatar: /assets/images/flo.png
  email: me@florian-bader.de
  url: florian-bader.de
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
